version: "3.9"  # optional since v1.27.0
services:
  auth_proxy:
    image: ghcr.io/conradludgate/spotify-auth-proxy
    ports:
      - "27228:27228"
    container_name: "auth_proxy"
    env_file:
      - ".env"